project:
  type: website
  output-dir: .

website:
  title: "Muhammad Al Hasib"

  navbar:
    left:
      - text: Home
        href: index.qmd
        
      - text: About
        href: about.qmd
        
      - text: Research
        href: research.qmd

      - text: CV
        href: cv.qmd

      - text: "EPPS 6323"
        menu:
          - text: "Coursework"
            href: assignments.html
            
          - text: "— Assignments —"
            href: assignments.html
            
          - text: "Assignment 01"
            href: assignment01.html
            
          - text: "Assignment 02"
            href: assignment02.html
            
          - text: "Assignment 03"
            href: assignment03.html
            
          - text: "Assignment 04"
            href: assignment04.html
            
          - text: "— Reflctions —"
            href: assignments.html
            
          - text: "Reflction 01"
            href: reflection01.html
            
          - text: "— Labs —"
            href: assignments.html
            
          - text: "Lab 01: R Programming Basics I"
            href: Lab01.html
            
          - text: "Lab 02: R Programming Basics II"
            href: Lab02.html
            
          - text: "Lab ML01: Simple and Multiple Linear Regression"
            href: Lab_ML01.html
        
  page-footer:
    center: "© 2026 Muhammad Al Hasib"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true